env_name: mountaincarcontinuous
gym_env_name: MountainCarContinuous-v0
logdir: logs/mountaincarcontinuous_sb3
reference_logdir: logs/mountaincarcontinuous_reflective_prompted_policy_optimization_s
num_trials: 10
budget_mode: episodes
budget_target: 4000
use_periodic_eval: true
eval_every_episodes: 1
eval_episodes: 20
render_mode: null
algorithms:
  - SAC
  - DDPG
  - TD3
  - A2C
  - PPO
  - TRPO
env_kwargs: {}
algorithm_hyperparams:
  DDPG:
    n_envs: 1
  TD3:
    n_envs: 1
  SAC:
    n_envs: 1
  A2C:
    n_envs: 1
  PPO:
    n_envs: 1
  TRPO:
    n_envs: 1
